### ISSUE TITLE
Not changing version number of ipa file.

### ISSUE THREAD

**Issue by tharindu-dif** [damienaicheh/update-ios-version-info-plist-action#1]
Hi I have used this library to change the version number for my iOS pipeline. Following is my GitHub Actions workflow snippet.

```
- name: Set iOS Version
        uses: damienaicheh/update-ios-version-info-plist-action@v1.0.0
        with:
          info-plist-path: 'iOS/proj/Info.plist'
          bundle-short-version-string: "1.0.0"
          bundle-version: '1'
          print-file: true
```
But the generated ipa file  still shows the version that has been set by Xcode. I will be posting the screenshot of my Ms AppCenter releases window as well.
<img width="300" alt="Screenshot 2022-04-29 at 17 57 18" src="https://user-images.githubusercontent.com/96049621/165944319-4fe3c941-262c-47af-b74b-86c8fd9e3fc2.png">

**Comment by damienaicheh** [comment]
Hi,

With your informations I can't help you. Check the logs of your workflow to be sure that the action doesn't apply correctly the version and show it to me. I m pretty sure that you have a mecanism that override the version or maybe you do it to late.

**Comment by tharindu-dif** [comment]
Hi @damienaicheh changing the version of info.plist file will be enough? Don't we need to change the version number of pbxproj file as well? 
I'm only executing xcodebuild command and export commands after this. I'm using separated plist file for export process but that doesn't contains any version number. I have added only iCloud configurations there. Following is my rest of the code.

```
      - name: Xcode Version
        run: /usr/bin/xcodebuild -version
        
      - name: Create build folder
        run: |
        mkdir -p build && mkdir -p staging 
        
      - name: Build Archive
        run: |
          xcodebuild -workspace $WORKPLACE -scheme $SCHEME -configuration $CONFIGURATION \
          archive -archivePath $ARCHIVE_PATH -allowProvisioningUpdates
          PROVISIONING_STYLE="Manual" \
          PROVISIONING_PROFILE={$DISTRIBUTION_PROFILE_STAGING} \
          CODE_SIGN_STYLE="Manual" \
          CODE_SIGN_IDENTITY={$DISTRIBUTION_CERTIFICATE} \
      - name: Export STAGING
        run: |
          xcodebuild -exportArchive -archivePath $ARCHIVE_PATH -exportPath $EXPORT_PATH_STAGING . -exportOptionsPlist $PLIST_PATH_STAGING \
```

**Comment by damienaicheh** [comment]
Hi, In my project I just change the version inside the info.plist I don't have any other reference instead of this one.

**Comment by tharindu-dif** [comment]
@damienaicheh I think that doesn't enough, For me seems like it's always taking the version of pbxproj file

<img width="560" alt="Screenshot 2022-05-02 at 13 45 00" src="https://user-images.githubusercontent.com/96049621/166205031-6e5a341e-484b-4086-b982-a693f822d408.png">

**Comment by damienaicheh** [comment]
Like I told you, in my project the version is ONLY specified in my info.plist I have nothing in my pbxproj files.

**Comment by tharindu-dif** [comment]
@damienaicheh How do you run an iOS project without having a pbxproj file? Is it automatically generated for any iOS project wether native or hybrid.

**Comment by damienaicheh** [comment]
I m using fastlane.

**Comment by tharindu-dif** [comment]
@damienaicheh I'm using GitHub actions. use `xcodebuild` command to build the spa file. Should this script be calling before the `xcodebuild` or should I execute is after the build process?

**Comment by damienaicheh** [comment]
Of course before the build. After the build everything is finished.
