### ISSUE TITLE
automate increasing bundle version

### ISSUE THREAD

**Issue by iamhaaamed** [damienaicheh/update-ios-version-info-plist-action#3]
Hi, is there any way to automate increasing bundle version, so we don't need to update it manually?

**Comment by HarelM** [comment]
I'm using github's `run_number`.
See the code here that I wrote to create a version based on my package.json file (I'm using npm mainly for major and minor numbers):
https://github.com/IsraelHikingMap/Site/blob/318bbf120689ea8f41b536a103c1737357d85886/.github/workflows/build-publish.yml#L46
And I'm applying the version number I created here to the plist info file using this github action:
https://github.com/IsraelHikingMap/Site/blob/318bbf120689ea8f41b536a103c1737357d85886/.github/workflows/build-publish.yml#L189

I'm using this version code for both android and iOS, and android need a version number which is not a string, so I'm doing some basic math there as well.

Hope that helps... Good luck!
