### ISSUE TITLE
The following actions uses node12 which is deprecated and will be forced to run on node16

### ISSUE THREAD

**Issue by aahlrichs5** [damienaicheh/update-ios-version-info-plist-action#4]
The following actions uses node12 which is deprecated and will be forced to run on node16: damienaicheh/update-ios-version-info-plist-action@v1.1.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by damienaicheh** [comment]
Upgrade to Node 20 directly. Thanks for your feedback.
